<?php

/**
 * Rangine crontab server
 *
 * (c) We7Team 2019 <https://www.rangine.com>
 *
 * document http://s.w7.cc/index.php?c=wiki&do=view&id=317&list=2284
 *
 * visited https://www.rangine.com for more details
 */

namespace W7\Crontab\Tests;

class TestCase extends \PHPUnit\Framework\TestCase {
	protected function setUp(): void {
		date_default_timezone_set('Asia/Shanghai');
		parent::setUp(); // TODO: Change the autogenerated stub
	}
}
